services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  bd:
    build: bd
    environment:
      DB_URL: ${DB_URL}
      AEG_KEY: ${AEG_KEY}
      BINANCE_PRIVATE_KEY: ${BINANCE_PRIVATE_KEY}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      TELEGRAM_USER_ID: ${TELEGRAM_USER_ID}
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  engine:
    build: engine_crypto
    depends_on:
      - bd

  binance_service:
    build: binance_query
    environment:
      AEG_KEY: ${AEG_KEY}
    depends_on:
      - engine
    ports:
      - 7070:7070

  tg_bot:
    build: telegram_bot
    depends_on:
      - binance_service
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_USER_ID: ${TELEGRAM_USER_ID}
